### ISSUE TITLE
Je krijgt ook mg1A

### ISSUE THREAD

**Issue by Theo-denBlanken** [kgeurts/PRO1---Formulieren#3]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
    <option value="MG1A">MG1A</option>
       <option value="MG1B">MG1B</option>
       <option value="MG1C">MG1C</option>
       <option value="MG1D">MG1D</option>
   </select> 
```

URL: https://github.com/kgeurts/PRO1---Formulieren/blob/master/index.html

Feedback: Als je niets selecteert. De aarste value leeg "" geven en required bij select[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"cd11d5bda92bf537657e504ae4d1474226ef99e5","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by kgeurts** [comment]
Toegevoegd!
