### ISSUE TITLE
Maak deze verplicht

### ISSUE THREAD

**Issue by Theo-denBlanken** [kgeurts/PRO1---Formulieren#4]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
label>Naam:</label> <input type="text" name="naam" placeholder="Vul hier je naam in">   
```

URL: https://github.com/kgeurts/PRO1---Formulieren/blob/master/index.html

Feedback: met attribuut required.[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"cd11d5bda92bf537657e504ae4d1474226ef99e5","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by kgeurts** [comment]
Toegevoegd!
